name: rca_resident
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  google_fonts:
  flutter_spinkit:
  shared_preferences: ^2.2.2
  line_icons: ^2.0.1
  get: 4.6.6
  dart_jsonwebtoken: ^2.13.0
  intl:
  qr_flutter: ^4.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

